name: build-static-site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Build (static export via next.config.mjs)
        run: |
          if npm run -s | grep -q "^  build$"; then
            npm run build
          else
            npx next build
          fi
          ls -la out || (echo "out/ not found - check next.config.mjs (output: 'export')" && exit 1)

      - name: Upload artifact (out)
        uses: actions/upload-artifact@v4
        with:
          name: site-out
          path: out

      - name: ZIP out
        if: always()
        run: |
          if [ -d out ]; then
            cd out
            zip -r ../site-out.zip .
          fi

      - name: Upload ZIP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: site-out-zip
          path: site-out.zip
          if-no-files-found: ignore
